In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import metrics
import seaborn as sb

In [12]:
data = pd.read_csv("C:\\Users\\Ashmita\\OneDrive\\Documents\\Deep Learning\\WineQT.csv")
data.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,1
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,2
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,3
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,4

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1143 entries, 0 to 1142
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1143 non-null   float64
 1   volatile acidity      1143 non-null   float64
 2   citric acid           1143 non-null   float64
 3   residual sugar        1143 non-null   float64
 4   chlorides             1143 non-null   float64
 5   free sulfur dioxide   1143 non-null   float64
 6   total sulfur dioxide  1143 non-null   float64
 7   density               1143 non-null   float64
 8   pH                    1143 non-null   float64
 9   sulphates             1143 non-null   float64
 10  alcohol               1143 non-null   float64
 11  quality               1143 non-null   int64
 12  Id                    1143 non-null   int64
dtypes: float64(11), int64(2)
memory usage: 116.2 KB

In [13]:
data.describe().T

,count,mean,std,min,25%,50%,75%,max
fixed acidity,1143.0,8.311111,1.747595,4.60000,7.10000,7.90000,9.100000,15.90000
volatile acidity,1143.0,0.531339,0.179633,0.12000,0.39250,0.52000,0.640000,1.58000
citric acid,1143.0,0.268364,0.196686,0.00000,0.09000,0.25000,0.420000,1.00000
residual sugar,1143.0,2.532152,1.355917,0.90000,1.90000,2.20000,2.600000,15.50000
chlorides,1143.0,0.086933,0.047267,0.01200,0.07000,0.07900,0.090000,0.61100
free sulfur dioxide,1143.0,15.615486,10.250486,1.00000,7.00000,13.00000,21.000000,68.00000
total sulfur dioxide,1143.0,45.914698,32.782130,6.00000,21.00000,37.00000,61.000000,289.00000
density,1143.0,0.996730,0.001925,0.99007,0.99557,0.99668,0.997845,1.00369
pH,1143.0,3.311015,0.156664,2.74000,3.20500,3.31000,3.400000,4.01000
sulphates,1143.0,0.657708,0.170399,0.33000,0.55000,0.62000,0.730000,2.00000
alcohol,1143.0,10.442111,1.082196,8.40000,9.50000,10.20000,11.100000,14.90000
quality,1143.0,5.657043,0.805824,3.00000,5.00000,6.00000,6.000000,8.00000
Id,1143.0,804.969379,463.997116,0.00000,411.00000,794.00000,1209.500000,1597.00000

In [15]:
x = data.drop(columns='quality')
y = data['quality']

In [16]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.30,random_state=1)

In [25]:
from sklearn.preprocessing import StandardScaler

In [26]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [31]:
print(x_train)

[[-0.37889286  0.14426676 -0.96434653 ...  0.01152837 -0.79148519
  -0.01367565]
 [-1.22463585 -0.55947353 -0.25067657 ... -0.33870056 -0.88651092
   0.83607347]
 [-0.04059566  0.76680625 -0.04677087 ... -0.74730097 -1.17158813
  -1.5961166 ]
 ...
 [-0.99910438  0.14426676 -0.65848798 ... -0.22195758  1.20405525
   1.57093303]
 [ 0.0157872   0.14426676 -0.96434653 ... -0.80567246  0.53887511
  -1.0325075 ]
 [-0.88633865  0.79387318 -0.301653   ... -0.33870056 -0.12630504
   1.46688212]]

In [27]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(x_train,y_train)

GaussianNB()

In [28]:
y_pred = model.predict(x_test)
metrics.confusion_matrix(y_test,y_pred)

array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  1,  4,  0,  0,  0],
       [ 3,  3, 88, 40,  6,  0],
       [ 0,  5, 33, 87, 23,  1],
       [ 0,  1,  5, 12, 23,  0],
       [ 0,  0,  0,  0,  8,  0]], dtype=int64)

In [29]:
from sklearn.metrics import accuracy_score

In [32]:
accuracy_score(y_test, y_pred)*100

58.01749271137027